Docs
Azure/iot-edge-opc-publisher-v1 pull request #263
Opened 2020-10-29 09:46 UTC by barnstee

Link to new OPC Publisher repo.

2020-10-30 15:58 UTC, dacolgit reviewed
I know it's just a visualization aspect, but I think it's better to have the same displaying format for Command Line argument of version '2.5' and '2.6 and above'.

-> Fixed.

2020-11-03 06:28 UTC, koepalex commented
_Readme.md_
* **in IEC62541 OPC UA PubSub standard format.** 2.5 publisher (in this repo) don't support PubSub, first sentence could be confusing

2020-11-03 06:28 UTC, koepalex approved these changes

2020-11-03 08:23 UTC, mregen commented on TelemetryFormatConfiguration.md
> +    // 1) The 'Defaults' object, which defines defaults for the telemetry configuration
I'd move pics and dependent md files to a docs folder.

2020-11-03 08:24 UTC, mregen commented on CommandLineArguments.md
> +          -c, --connectionstring=VALUE
formatting

2020-11-03 08:24 UTC, mregen commented on CommandLineArguments.md
> +                                       the 'ApplicationURI' property when telemetry is
formatting

2020-11-03 08:27 UTC, mregen commented on CommandLineArguments.md
> +        iothubconnectionstring: the IoTHub owner connectionstring, optional. Typically you specify the IoTHub owner connectionstring 	 only on the first start of the application. The connectionstring
> only on the first start of the appli [](start = 134, length = 37)

The latter portion of the sentence is invisible in the preview here: [https://github.com/Azure/iot-edge-opc-publisher/blob/docs/CommandLineArguments.md](https://github.com/Azure/iot-edge-opc-publisher/blob/docs/CommandLineArguments.md)

2020-11-03 08:30 UTC, mregen commented on CommandLineArguments.md
> +    	On subsequent calls it will be read from there and reused. If you specify the connectionstring on each start, the device 		which is created for the application in the IoTHub device registry will
>which is created for the application in the IoTHub device registry will be removed and recreate [](start = 128, length = 95)

same as above

2020-11-03 08:32 UTC, mregen commented on CommandLineArguments.md
> +                                       Default: False
>  Default: False [](start = 37, length = 16)

I'd align these values with the start of sentence, so they better stand out

2020-11-03 08:37 UTC, mregen commented on CommandLineArguments.md
> +                                       it will be sent.
>will [](start = 42, length = 4)

in general I'm not a big fan of future tense in technical documentation

2020-11-03 08:37 UTC, mregen commented on CommandLineArguments.md
> +                                     the max size of a message which can be send to
>send [](start = 76, length = 4)

sent

2020-11-03 08:38 UTC, mregen commented on CommandLineArguments.md
> +                                       IoTHub. when telemetry of this size is available
>when [](start = 47, length = 4)

When

2020-11-03 08:40 UTC, mregen commented on CommandLineArguments.md
> +                                       applicationname> manually and pass in the
poor line braek

2020-11-03 08:40 UTC, mregen commented on CommandLineArguments.md
> +                                       send to IoTHub. If 0, then only the
>send [](start = 39, length = 4)

sent?

2020-11-03 08:42 UTC, mregen commented on CommandLineArguments.md
> +                                       multiple thumbprints supported)
how to specify multiple?

2020-11-03 08:44 UTC, mregen commented on CommandLineArguments.md
> +              --st, --opcstacktracemask=VALUE
formatting

2020-11-03 09:10 UTC, mregen commented on CommandLineArguments.md
> +### OPC Publisher Command Line Arguments for Version 2.6 and above
>on 2.6 a [](start = 50, length = 8)

why 2.6. options here?

2020-11-03 09:10 UTC, mregen requested changes
:clock1:

2020-11-03 09:11 UTC, mregen commented on opcpublisher.sln
> +		CommandLineArguments.md = CommandLineArguments.md
>CommandLineArguments.md = CommandLineArguments.md [](start = 2, length = 49)

I'd not add doc and license files to solutions

2020-11-03 09:45 UTC, mregen commented on TelemetryFormatConfiguration.md
> +    // The configuration settings file consists of two objects:
>/ The configuration s [](start = 5, length = 21)

The page has no header / description

2020-11-03 14:20 UTC, barnstee reviewed
> _Readme.md_
> 
> * **in IEC62541 OPC UA PubSub standard format.** 2.5 publisher (in this repo) don't support PubSub, first sentence could be confusing

Fixed.

2020-11-03 14:20 UTC, barnstee commented on CommandLineArguments.md
> +        iothubconnectionstring: the IoTHub owner connectionstring, optional. Typically you specify the IoTHub owner connectionstring 	 only on the first start of the application. The connectionstring
Strange, it renders correctly in my MD editor. Will fix.

2020-11-03 14:22 UTC, merged