Use OPC subscriptions for each publishing interval, remove model compiler, update readme, and various more
Azure/iot-edge-opc-publisher-v1 pull request #78
Opened 2017-09-24 15:46 UTC by hansgschossmann

This merge will not be the final one, since there is a blocking issue for error free operation in docker scenarios, which will be resolved with a fix in the OPC UA stack most likely with [issue #218](https://github.com/OPCFoundation/UA-.NETStandardLibrary/issues/218). The current stack only takes the first IPv4 and IPv6 addresses returned by the OS into account. This could lead to non connectivity if the target OPC UA server is only reachable via other addresses.

The PR brings in:
- Establish a separate subscription for each publishing interval to a certain endpoint URL
- Remove the model compiler and create the address space programmatically.
- Update the readme.md with the current information
- Add protection of shared data structures
- Change PublishNode and UnpublishNode to support new application architecture
- Use string NodeId's in address space and remove the integer NodeId's
- Change Dockerfile and add a SSH only Dockerfile for SSH debugging in a docker container

2017-09-24 15:46 UTC, msftclas commented
@hansgschossmann,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-09-25 07:51 UTC, mregen approved these changes
First walkthrough...
Overall seems good.
A little concerned on the Wait/async mix when using semaphores.

2017-09-25 07:51 UTC, mregen commented on src/IotHubMessaging.cs
>                  Trace(Utils.TraceMasks.OperationDetail, $"Retart timer to send data to IoTHub in {_defaultSendIntervalSeconds} second(s).");
typo 'restart'

2017-09-25 07:51 UTC, mregen commented on src/Namespaces.cs
> +        public const string PublisherApplications = "http://opcfoundation.org/UA/Publisher/";
Should the namespace URI be rather microsoft.com?

2017-09-25 07:51 UTC, mregen commented on src/OpcSession.cs
>              _opcSessionSemaphore.Wait();
better use await?

2017-09-25 07:51 UTC, mregen commented on src/OpcSession.cs
> +                Task.Run(async () => await ConnectAndMonitor());
connect always even on error condition?

2017-09-25 07:51 UTC, mregen commented on src/OpcSession.cs
>              _opcSessionSemaphore.Wait();
I'd avoid blocking calls wherever possible, e.g. await semaphore.WaitAsync() instead of Wait

2017-09-25 13:48 UTC, barnstee requested changes

2017-09-25 13:48 UTC, barnstee commented on Dockerfile
> +WORKDIR /docker
Not sure this will work as the working directory needs to be the publishing directory

2017-09-25 13:48 UTC, barnstee commented on README.md
> +Publisher implements a retry logic to establish connections to endpoints which have not responded to a certain number of keep alive requests, if the OPC UA server on this endpoint had a power outage.
... for example if the OPC UA server...

2017-09-25 13:48 UTC, barnstee commented on README.md
> +For each distinct publishing interval to a OPC UA server it creates a separate subscription over which all nodes with this publishing interval are updated.
an OPC

2017-09-25 13:48 UTC, barnstee commented on README.md
> +Publisher supports aggregation of the data sent to IoTHub, to reduce network load. This batching is sending a packet to IoTHub only if the configured package size is reached.
I wouldn't call it aggregation, as this is something else on OPC UA. Call it batching throughout.

2017-09-25 13:48 UTC, barnstee commented on README.md
> +The `-f` option for `docker build` is optional and the default is to use Dockerfile. Docker also support building directly from a git repository, which means you also could build a Linux container by
can, not could

2017-09-25 13:48 UTC, barnstee commented on README.md
> +            // Publisher will request the server at EndpointUrl to sample the node with the OPC sampling interval specified on command line (or the default value: OPC publishing interval).
I wouldn't put in the comments on every node.

2017-09-25 13:48 UTC, barnstee commented on README.md
> +                               ingested to IoTHub.
sent, not ingested

2017-09-25 13:48 UTC, barnstee commented on README.md
> +There are a couple of environment variables which could be used to control the application:
can, not could

2017-09-25 13:48 UTC, barnstee commented on README.md
> +Open the OpcPublisher.sln project with Visual Studio 2017, build the solution and publish it. You could start the application in the 'Target directory' you have published to with:
can, not could

2017-09-25 13:48 UTC, barnstee commented on README.md
> +The Publisher container could now be reached by other containers via the name `publisher`over the network.
can, not could

2017-09-25 13:48 UTC, barnstee commented on README.md
> +### Access to the host network
this isn't access to the host network, this is access to the publisher container network. I would not document this but actually describe how  --network=host works.

2017-09-25 13:48 UTC, barnstee commented on README.md
> +Another debugging option VS2017 supports is to debug via ssh. In the root of the repository the docker build configuration file `Dockerfile.ssh`could be used to create a SSH enabled container by:
can, not could

2017-09-25 13:48 UTC, barnstee commented on README.md
> +Use a tool like WinSCP to copy over the published files to the container into the directory `/root/publisher` (this could be also a different directory, but needs to be in sync with the `cdw` propert
can, not could

2017-09-25 13:48 UTC, barnstee commented on README.md
> +Now you could start debugging with the following command in Visual Studio's Command Window (View->Other Windows->Command Window):
can, not could

2017-09-25 13:48 UTC, barnstee commented on src/OpcPublisher.csproj
> +    <Description>This package subscribes to a configurable set of nodes in OPC UA server systems and publish them to Azure IoTHub.</Description>
application, not package

2017-09-25 13:48 UTC, barnstee commented on src/OpcSession.cs
> +                // find a subscription we could the node monitor on
Grammar...

2017-09-25 13:48 UTC, barnstee commented on src/OpcStackConfiguration.cs
> +            Configuration.TransportQuotas.MaxStringLength = 1048576;
Please reduce these again

2017-09-25 13:48 UTC, barnstee commented on src/Program.cs
> +                        // create for all different OPC publishing intervals to this endpoint separate subscriptions
Grammar...

2017-09-25 13:48 UTC, barnstee commented on src/PublisherServer.cs
> +        protected override void OnServerStarted(IServerInternal server)
Please remove since this is not used (see implementation below).

2017-09-28 06:06 UTC, hansgschossmann commented on src/IotHubMessaging.cs
>                  Trace(Utils.TraceMasks.OperationDetail, $"Retart timer to send data to IoTHub in {_defaultSendIntervalSeconds} second(s).");
fixed

2017-09-28 06:07 UTC, hansgschossmann commented on src/Namespaces.cs
> +        public const string PublisherApplications = "http://opcfoundation.org/UA/Publisher/";
will change to: http://microsoft.com/Opc/Publisher/

2017-09-28 06:07 UTC, hansgschossmann commented on src/OpcSession.cs
> +                Task.Run(async () => await ConnectAndMonitor());
great catch. thx

2017-09-28 06:08 UTC, hansgschossmann commented on src/OpcSession.cs
>              _opcSessionSemaphore.Wait();
yes that makes sense. fixed

2017-09-28 06:09 UTC, hansgschossmann commented on src/OpcSession.cs
>              _opcSessionSemaphore.Wait();
yes that makes sense. fixed

2017-09-28 06:09 UTC, hansgschossmann commented on Dockerfile
> +WORKDIR /docker
it works

2017-09-28 06:09 UTC, hansgschossmann commented on README.md
> +Publisher implements a retry logic to establish connections to endpoints which have not responded to a certain number of keep alive requests, if the OPC UA server on this endpoint had a power outage.
fixed

2017-09-28 06:09 UTC, hansgschossmann commented on README.md
> +For each distinct publishing interval to a OPC UA server it creates a separate subscription over which all nodes with this publishing interval are updated.
fixed

2017-09-28 06:10 UTC, hansgschossmann commented on README.md
> +Publisher supports aggregation of the data sent to IoTHub, to reduce network load. This batching is sending a packet to IoTHub only if the configured package size is reached.
fixed

2017-09-28 06:10 UTC, hansgschossmann commented on README.md
> +The `-f` option for `docker build` is optional and the default is to use Dockerfile. Docker also support building directly from a git repository, which means you also could build a Linux container by
fxied

2017-09-28 06:10 UTC, hansgschossmann commented on README.md
> +            // Publisher will request the server at EndpointUrl to sample the node with the OPC sampling interval specified on command line (or the default value: OPC publishing interval).
changed to a complete new format

2017-09-28 06:10 UTC, hansgschossmann commented on README.md
> +                               ingested to IoTHub.
fixed

2017-09-28 06:10 UTC, hansgschossmann commented on README.md
> +There are a couple of environment variables which could be used to control the application:
fixed

2017-09-28 06:10 UTC, hansgschossmann commented on README.md
> +Open the OpcPublisher.sln project with Visual Studio 2017, build the solution and publish it. You could start the application in the 'Target directory' you have published to with:
fixed

2017-09-28 06:11 UTC, hansgschossmann commented on README.md
> +### Access to the host network
host network documentation is sparse, almost not there. but you are right it does not enable host network access, but inter container name resolution. changed

2017-09-28 06:11 UTC, hansgschossmann commented on README.md
> +The Publisher container could now be reached by other containers via the name `publisher`over the network.
fixed

2017-09-28 06:12 UTC, hansgschossmann commented on README.md
> +Another debugging option VS2017 supports is to debug via ssh. In the root of the repository the docker build configuration file `Dockerfile.ssh`could be used to create a SSH enabled container by:
fixed

2017-09-28 06:12 UTC, hansgschossmann commented on README.md
> +Now you could start debugging with the following command in Visual Studio's Command Window (View->Other Windows->Command Window):
fixed

2017-09-28 06:12 UTC, hansgschossmann commented on src/OpcSession.cs
> +                // find a subscription we could the node monitor on
fixed

2017-09-28 06:12 UTC, hansgschossmann commented on src/PublisherServer.cs
> +        protected override void OnServerStarted(IServerInternal server)
removed

2017-09-28 06:12 UTC, hansgschossmann commented on src/Program.cs
> +                        // create for all different OPC publishing intervals to this endpoint separate subscriptions
fixed

2017-09-28 06:12 UTC, hansgschossmann commented on src/OpcStackConfiguration.cs
> +            Configuration.TransportQuotas.MaxStringLength = 1048576;
done

2017-09-28 06:12 UTC, hansgschossmann commented on src/OpcPublisher.csproj
> +    <Description>This package subscribes to a configurable set of nodes in OPC UA server systems and publish them to Azure IoTHub.</Description>
changed

2017-09-28 07:38 UTC, mregen commented on src/Namespaces.cs
> +        public const string PublisherApplications = "http://opcfoundation.org/UA/Publisher/";
I checked the spec, (Part 6 F14 has a sample) it should be ok like this

---
In reply to: [141532429](https://github.com/Azure/iot-edge-opc-publisher/pull/78#discussion_r141532429) [](ancestors = 141532429)

2017-09-28 08:20 UTC, barnstee approved these changes

2017-09-28 08:20 UTC, barnstee commented on README.md
> +For each distinct publishing interval to aanOPC UA server it creates a separate subscription over which all nodes with this publishing interval are updated.
typo

2017-09-28 08:21 UTC, barnstee commented on Dockerfile
> +WORKDIR /docker
ok

2017-09-29 11:28 UTC, hansgschossmann commented on README.md
> +For each distinct publishing interval to aanOPC UA server it creates a separate subscription over which all nodes with this publishing interval are updated.
fixed

2017-09-29 11:42 UTC, merged